### PR TITLE
Removed 2 not not in user terms

### PR DESCRIPTION
**Pull request by ShobanChiddarth**
There were 2 not and I removed one

### CODE REVIEW

**Review by elephantman-del — COMMENTED** [review]
Hey George how abouts you quit stealing my shit off my phone asshole ..I'll be giving this to the cops ...I hope you and your friend rot in a cell

**Comment by Lzsolo1** [comment]
What are you talking about, are you human! ?

នៅ​ថ្ងៃទី សៅរ៍ 7 ស.ហ 2021, 8:06 PM elephantman-del ***@***.***>
បាន​សរសេរ​ថា៖

**Comment by mercur1114** [comment]
Hasan pekyürek

**Comment by mercur1114** [comment]
> Hey George how abouts you quit stealing my shit off my phone asshole ..I'll be giving this to the cops ...I hope you and your friend rot in a cell

**Comment by TheeConductor1** [comment]
Thank you

**Pull request merged**
