### PR TITLE
Add more info in the README description

### PR DESCRIPTION
**Pull request by SuperDragonXD**
For easier findability.

### CODE REVIEW

**Comment by zacharee** [comment]
The terms.md file needs to stay in the assets folder, since it's referenced by the app itself.

**Comment by SuperDragonXD** [comment]
If so, then I'll just rename the PR to 'add more info in the description of the README.md' Is it ok?

**Comment by SuperDragonXD** [comment]
I also reverted the changes

**Comment by SuperDragonXD** [comment]
Uh... there isn't any... It only shows "Building" when you go to [Tweaker Home](https://github.com/zacharee/Tweaker)

**Comment by zacharee** [comment]
https://github.com/SuperDragonXD/Tweaker

It's still in your source branch.

**Comment by SuperDragonXD** [comment]
What do you mean?

**Comment by eyogl** [comment]
Listo

**Pull request closed without merging**
